@startuml
left to right direction

:Customer: as customer
:Employee: as employee

rectangle TravelAgency{
(Manage bookings) as (manage-bookings)
(Sell bookings) as (sell-bookings)
(See Statistic of sold bookings) as (booking-statistics)

customer --> (manage-bookings)
employee --> (sell-bookings)
employee --> (booking-statistics)
}
@enduml